// HANDBOOK_SIDEBAR_* — does the sidebar shape agree with the declared Starlight?
//
// Starlight 0.39 removed the top-level autogenerate key on a labelled sidebar
// group and added the nested `items: [{ autogenerate }]` form. The two are
// mutually exclusive, which was verified by building rather than assumed
// (2026-09-17):
//
//   Starlight 0.37.7, nested form:
//     Expected type `{ label, link } | { label, items } | { label } | { slug } | string`
//   Starlight 0.42.1, labelled form:
//     Support for autogenerated sidebar groups was removed in Starlight v0.39.0
//
// So neither shape is "the old one" and the rule cannot be one-directional.
// A whole fleet of repos can carry the labelled shape and be green, because a
// caret on a 0.x version pins the minor. Reporting the shape alone would be
// one confident, wrong finding per repo.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { sidebarShape, starlightRange, rangeAdmits039 } from '../src/load.mjs';

const cfg = (sidebar) => `import starlight from '@astrojs/starlight';
export default defineConfig({ integrations: [starlight({
  title: 'X',
  social: [{ icon: 'github', label: 'GitHub', href: 'https://example.com' }],
  sidebar: ${sidebar},
})] });`;

test('labelled autogenerate is detected in both orderings and both layouts', () => {
  // The one-line form and the expanded form, both seen in real configs.
  assert.equal(sidebarShape(cfg(`[{ label: 'Handbook', autogenerate: { directory: 'handbook' } }]`)),
    'labeled-autogenerate');
  assert.equal(sidebarShape(cfg(`[
    {
      label: 'Handbook',
      autogenerate: { directory: 'handbook' },
    },
  ]`)), 'labeled-autogenerate');
  // Key order is not guaranteed by anything, so both are matched.
  assert.equal(sidebarShape(cfg(`[{ autogenerate: { directory: 'handbook' }, label: 'Handbook' }]`)),
    'labeled-autogenerate');
});

test('a sibling `label` elsewhere in the config is not a sidebar group', () => {
  // Every scaffolded config carries `social: [{ icon, label, href }]`. Matching
  // that would make every repo look broken.
  assert.equal(sidebarShape(cfg(`[{ label: 'Handbook', items: [{ autogenerate: { directory: 'handbook' } }] }]`)),
    'items-autogenerate');
});

test('multiple labelled groups still resolve to the labelled shape', () => {
  // One real config declares six of them.
  assert.equal(sidebarShape(cfg(`[
    { label: 'Getting Started', autogenerate: { directory: 'handbook/getting-started' } },
    { label: 'Product', autogenerate: { directory: 'handbook/product' } },
  ]`)), 'labeled-autogenerate');
});

test('prose about the migration is not mistaken for the migration', () => {
  // Real configs carry a comment explaining the 0.39 change directly above the
  // fixed code. Matching the commentary would report the repos that had
  // already fixed it.
  const src = cfg(`[
    // Starlight 0.39 removed top-level \`autogenerate\` on a group with a label;
    // the autogenerate config now lives inside \`items\`.
    { label: 'Handbook', items: [{ autogenerate: { directory: 'handbook' } }] },
  ]`);
  assert.equal(sidebarShape(src), 'items-autogenerate');
});

test('a hand-written sidebar is valid on every version and never a finding', () => {
  // A repo can move here deliberately, to order its pages by hand.
  assert.equal(sidebarShape(cfg(`[{ label: 'Handbook', items: [{ slug: 'handbook/intro' }] }]`)),
    'explicit');
});

test('unmeasured and absent are different answers', () => {
  assert.equal(sidebarShape(undefined), null, 'no site/astro.config.mjs, or a pre-collection snapshot');
  assert.equal(sidebarShape('export default defineConfig({});'), 'none', 'a config with no sidebar at all');
});

test('a caret on a 0.x range pins the MINOR — this is why the old shape stays green', () => {
  // ^0.37.6 resolves to 0.37.x and never to 0.39. Treating caret as "any newer
  // minor" would report every one of those repos as broken today.
  assert.equal(rangeAdmits039('^0.37.6'), false);
  assert.equal(rangeAdmits039('^0.38.2'), false);
  assert.equal(rangeAdmits039('0.37.6'), false, 'exact pin');
  assert.equal(rangeAdmits039('^0.42.1'), true, 'a range past the boundary');
  assert.equal(rangeAdmits039('~0.39.0'), true, 'the boundary itself');
  assert.equal(rangeAdmits039('^1.0.0'), true, 'past 0.x entirely');
});

test('an unreadable range is not a verdict', () => {
  // The analyzer stays silent on these rather than guessing a direction.
  assert.equal(rangeAdmits039('latest'), null);
  assert.equal(rangeAdmits039(undefined), null);
  assert.equal(rangeAdmits039(null), null);
});

test('the declared range is read from either dependency block', () => {
  assert.equal(starlightRange('{"dependencies":{"@astrojs/starlight":"^0.37.6"}}'), '^0.37.6');
  assert.equal(starlightRange('{"devDependencies":{"@astrojs/starlight":"^0.42.1"}}'), '^0.42.1');
  assert.equal(starlightRange('{"dependencies":{"astro":"^5.0.0"}}'), null, 'no Starlight at all');
  assert.equal(starlightRange('not json'), null);
  assert.equal(starlightRange(undefined), null);
});

test('the real incident shape classifies as incompatible', () => {
  // Two sites, as they stood at the moment a Dependabot bump merged: labelled
  // shape, range widened past the boundary.
  const shape = sidebarShape(cfg(`[{ label: 'Handbook', autogenerate: { directory: 'handbook' } }]`));
  const admits = rangeAdmits039(starlightRange('{"dependencies":{"@astrojs/starlight":"^0.42.1"}}'));
  assert.equal(shape, 'labeled-autogenerate');
  assert.equal(admits, true, 'shape and range disagree -> HANDBOOK_SIDEBAR_INCOMPATIBLE');
});

test('the same shape below the boundary is bump risk, not breakage', () => {
  // The other 60. Correct for what they pin; broken the moment it widens.
  const shape = sidebarShape(cfg(`[{ label: 'Handbook', autogenerate: { directory: 'handbook' } }]`));
  const admits = rangeAdmits039(starlightRange('{"dependencies":{"@astrojs/starlight":"^0.37.6"}}'));
  assert.equal(shape, 'labeled-autogenerate');
  assert.equal(admits, false, 'shape and range agree -> HANDBOOK_SIDEBAR_BUMP_RISK');
});
